name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Install cargo expand
      run: cargo install cargo-expand
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run clippy
      run: cargo clippy -- --D warnings
    - name: Run tests
      run: cargo test --verbose --all-features
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt
    - name: Run fmt check
      run: cargo +nightly fmt --check
